kind: Deployment
apiVersion: apps/v1
metadata:
  name: pv-test
spec:
  replicas: 2
  selector:
    matchLabels:
      name: persistentvol-test
  template:
    metadata:
      name: pv-test
      labels:
        name: persistentvol-test
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
           - containerPort: 80
          resources:
            requests:
              cpu: 1
              memory: 500Mi
            limits: 
              cpu: 2
              memory: 1Gi
          volumeMounts:
            - name: local
              mountPath: /env/test/data
      volumes:
       - name: local
         persistentVolumeClaim:
          claimName: persistent-vol-claim
