kind: PersistentVolume
apiVersion: v1
metadata:
  name: persistent-vol
spec:
  #storageClassName: manual
  persistentVolumeReclaimPolicy: Recycle
  capacity: 
    storage: 2Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: /env/data



        

  
