kind: Deployment
apiVersion: apps/v1
metadata:
  name: request-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: request-deploy
  template:
    metadata:
      name: request-deployment
      labels:
        name: request-deploy
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
         - containerPort: 80
        resources:
          requests:
            cpu: 0.5
            memory: 100Mi