#kubectl create secret generic my-gen-secret --from-file=user.text --from-file=pass.text
kind: Deployment
apiVersion: apps/v1
metadata:
  name: env-deploy-secret
spec:
  replicas: 1 
  selector:
    matchLabels:
      name: secret-env
  template:
    metadata:
      name: env-deploy-secret
      labels:
        name: secret-env
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
          - containerPort: 80
          env:
          - name: user
            valueFrom:
              secretKeyRef:
                name: my-gen-secret
                key: user.text
          - name: pass
            valueFrom:
              secretKeyRef:
                name: my-gen-secret
                key: pass.text
