#kubectl create secret generic my-gen-secret --from-file=user.text --from-file=pass.text
kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      name: secret-deployment
  template:
    metadata:
      name: deploy-secret
      labels:
        name: secret-deployment
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
         - containerPort: 80
        resources:
          requests: 
            cpu: 0.5
            memory: 10Mi
          limits:
            cpu: 0.5
            memory: 200Mi
        volumeMounts:
        - name: my-vol-secret
          mountPath: /tmp/secrets/loc
      volumes:
        - name: my-vol-secret
          secret: 
            secretName: my-gen-secret
            optional: true
          
